### PR TITLE
Heavy Refactor and /AUS SteerCo init

### PR DESCRIPTION
**Pull request by XertroV**
- Move all branches into docs/branches/aus-<STATE> folder (to be compatible with internationalisation)
- Autogenerate constitutions from github (see ./scripts/)
- use POSIX path notation for referring to branches
- allow markdown files
- update requirements
- modify makefile to support autogeneration and more commands
- add Aus SteerCo init stuff

### CODE REVIEW

**Comment by XertroV** [comment]
@pwhipp - See here for a built version on readthedocs with the refactors: https://docs.flux.party/en/refactor-and-steerco/docs/constitutions/index.html#

I think things like using the posix path for branch names (in docs at least) is a good thing to do since it's highly scalable and self-organises (e.g. via sorting alphabetically). You can see how I've started to standardise things.

Let me know your thoughts.

**Comment by XertroV** [comment]
Note: I've removed the constitutions from the repository totally now - the idea is they're downloaded and converted (via pandoc) on every build. That means we don't need to worry about them and we can make sure they're as accurate as possible (while still being a copy).

Other stuff (like notes, updates on positions, etc) should go outside that section. See the /branches/aus folder for an example.

**Comment by XertroV** [comment]
@pwhipp - if you have no objections I'm going to merge this tomorrow morning.

**Comment by pwhipp** [comment]
@XetroV: Sorry, been busy with other stuff.

**Comment by XertroV** [comment]
@pwhipp 

> Using the pathname for the document name is redundant in a sense (its 'full' name includes its pathname) so it might be better to twink the sphinx presentation and take advantage of this. Having the pathname in the doc raises the complexity of refactoring the structure which will happen a lot over time.

Mm - are there any common solutions to this? At least Sphinx will warn you when links and TOC doens't line up.

> I would not worry about the internationalisation until its a problem. We need to keep things as simple as possible to get people on board.

Agreed - except insofar as avoiding tech-debt. Would prefer to just add "aus-" for the moment to avoid having complications down the line (like those that you referenced above wrt refactors / pathnames)

**Comment by pwhipp** [comment]
> Mm - are there any common solutions to this? At least Sphinx will warn you when links and TOC doens't line up.

Not that I know of. The link and breadcrumb get close to providing it by default.

**Pull request merged**
